package com.eventmanager.service;

import com.eventmanager.model.Hackathon;
import com.eventmanager.repository.HackathonRepository;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;

@Service
public class ScoringReportService {

    @Autowired
    private ScoringService scoringService;

    @Autowired
    private HackathonRepository hackathonRepository;

    public byte[] generateLeaderboardPdf(String hackathonId) throws IOException {
        Hackathon hackathon = hackathonRepository.findById(hackathonId)
                .orElseThrow(() -> new RuntimeException("Hackathon not found"));

        List<Map<String, Object>> leaderboard = scoringService.getLeaderboard(hackathonId);

        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, out);

            document.open();

            // Font styles
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font cellFont = FontFactory.getFont(FontFactory.HELVETICA, 11);

            // Title
            Paragraph title = new Paragraph(hackathon.getTitle() + " - Leaderboard", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // Table
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.setWidths(new float[] { 1, 4, 3, 2 });

            // Headers
            addTableHeader(table, "Rank", headerFont);
            addTableHeader(table, "Team Name", headerFont);
            addTableHeader(table, "Project Title", headerFont);
            addTableHeader(table, "Final Score", headerFont);

            // Data
            int rank = 1;
            for (Map<String, Object> entry : leaderboard) {
                table.addCell(new PdfPCell(new Phrase(String.valueOf(rank++), cellFont)));
                table.addCell(new PdfPCell(new Phrase((String) entry.get("teamName"), cellFont)));
                table.addCell(new PdfPCell(new Phrase((String) entry.get("projectTitle"), cellFont)));
                table.addCell(new PdfPCell(new Phrase(String.format("%.2f", (Double) entry.get("score")), cellFont)));
            }

            document.add(table);

            Paragraph footer = new Paragraph("\nGenerated by Smart Inter-College Hackathon Manager", 
                FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10));
            footer.setAlignment(Element.ALIGN_RIGHT);
            document.add(footer);

            document.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new IOException("Error generating PDF", e);
        }
    }

    private void addTableHeader(PdfPTable table, String headerTitle, Font font) {
        PdfPCell header = new PdfPCell();
        header.setBackgroundColor(java.awt.Color.LIGHT_GRAY);
        header.setBorderWidth(1);
        header.setPhrase(new Phrase(headerTitle, font));
        header.setPadding(5);
        table.addCell(header);
    }
}
